remote_theme: SotiriosVrachas/jekyll-theme-startbootstrap-agency 

title: The Rivers
description: The Rivers are a groove-driven acapella vocal group based in Oxford
author: MJP

sass: # Enables the conversion of css/agency.min.scss to  css/agency.min.css
  style: compressed # Minify css/agency.min.css

collections: # Enables additional data structures 
  projects: # Enables _projects
  
$primary: 0099cc !default;

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/millipz
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket 
    url:
  - title: github
    url: http://github.com/millipz

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
